destination_search_task:
  description: >
    Research destination {destination} for travel from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}, {accomodation}, {flights}, {origin}
  depends_on: []  # This is the initial task with no dependencies
  metadata:
    version: "1.0"
    priority: 1
    estimated_duration: "5m"
  required_params:
    - destination
    - start_date
    - end_date
    - budget
    - travelers
    - trip_type
  expected_output: >
    A comprehensive destination overview including current weather conditions,
    upcoming events, entry requirements, safety considerations, cultural insights,
    optimal visiting times, transportation options, financial preparation tips,
    local insider knowledge, and any recent developments affecting travelers.
  agent: travel_searcher

flight_search_task:
  description: >
    Search flights using multiple sources for {origin} to {destination}.
    Consider: {budget}, {travelers}, {trip_type}, {start_date}, {end_date}, {flights}
  depends_on:
    - destination_search_task  # Needs destination information first
  metadata:
    version: "1.0"
    priority: 2
    estimated_duration: "10m"
  required_params:
    - origin
    - destination
    - start_date
    - end_date
    - budget
    - travelers
  expected_output: >
    A detailed flight analysis including best-value options, comprehensive price comparisons,
    flight schedules, layover details, baggage policies, and travel requirements. Includes
    alternative airport suggestions, seasonal travel insights, and personalized recommendations
    based on comfort, convenience, and budget considerations.
  agent: travel_searcher

accommodation_search_task:
  description: >
    Search accommodations in {destination} from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}, {accomodation}
  depends_on:
    - destination_search_task  # Needs destination information first
  expected_output: >
    A curated selection of accommodations matching the specified criteria, highlighting
    best-value options across different price ranges. Each option includes detailed
    information about location, amenities, room types, accessibility features, and
    total cost breakdown, ensuring the perfect match for comfort and budget requirements.
  agent: travel_searcher

transportation_search_task:
  description: >
    Research local transportation in {destination} from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
  expected_output: >
    A comprehensive transportation guide covering all available options from public
    transit to private services. Includes detailed pricing for different pass types,
    coverage areas, taxi services, and rental options, helping travelers make
    informed decisions about local mobility during their stay.
  agent: travel_searcher

attraction_search_task:
  description: >
    Research attractions in {destination} for {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
    - transportation_search_task  # Useful to know transport options to attractions
  expected_output: >
    A carefully selected list of attractions categorized by type and cost, from free
    activities to premium experiences. Each attraction includes essential details about
    visiting duration, operating hours, and optimal timing recommendations to maximize
    the experience while staying within budget.
  agent: travel_searcher

dining_search_task:
  description: >
    Research dining options in {destination}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
    - accommodation_search_task  # Useful to know restaurant proximity to accommodation
  expected_output: >
    A diverse selection of dining options spanning various cuisines and price points,
    from local street food to fine dining experiences. Each recommendation includes
    location details, price ranges, and special highlights, ensuring memorable
    culinary experiences throughout the trip.
  agent: travel_searcher

structure_itinerary_task:
  description: >
    Create daily itinerary from {start_date} to {end_date}.
    Consider: {travelers}, {trip_type}
  depends_on:
    - flight_search_task  # Need flight timings
    - accommodation_search_task  # Need accommodation details
    - transportation_search_task  # Need local transport options
    - attraction_search_task  # Need attraction details
    - dining_search_task  # Need dining options
  expected_output: >
    A well-balanced day-by-day itinerary that seamlessly integrates all planned
    activities, dining, and transportation. Each day is thoughtfully structured with
    precise timing and duration estimates, ensuring a smooth and enjoyable travel
    experience that maximizes the destination's highlights.
  agent: itinerary_planner

create_travel_document_task:
  description: >
    Create a comprehensive travel document in Markdown format with all trip details.
    Consider: {start_date}, {end_date}, {travelers}, {trip_type}.
  depends_on:
    - flight_search_task  # Need flight timings
    - accommodation_search_task  # Need accommodation details
    - transportation_search_task  # Need local transport options
    - attraction_search_task  # Need attraction details
    - dining_search_task  # Need dining options
    - structure_itinerary_task  # Need validated itinerary
  expected_output: >
    A comprehensive travel document in Markdown format containing all essential trip
    details, practical information, recommendations, recommended flight option, recommended accommodation option, and useful
    resources. Organized in a clear, easy-to-reference format for convenient access
    during the journey.
  agent: quality_assurance


prepare_travel_email_task:
  description: >
    Prepare and send a beautifully formatted HTML email with all trip details to {recipient_email}.
    Convert markdown content to responsive HTML with CSS styling.
    Translate the content to {locale} language. Add multimedia resources like images and maps to enhance visual appeal.
  depends_on:
    - create_travel_document_task  # Need the final travel document to create email
  required_params:
    - recipient_email  # Email address must be provided
    - locale  # Language preference for email content
  expected_output: >
    A beautifully formatted, responsive HTML email containing the complete trip details,
    translated into the specified language. Includes delivery confirmation and status
    updates to ensure successful communication of all travel information to the recipient.
  agent: ui_designer





