destination_search_task:
  description: >
    Research destination {destination} for travel from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}, {accomodation}, {flights}, {origin}
  depends_on: []  # This is the initial task with no dependencies
  metadata:
    version: "1.0"
    priority: 1
    estimated_duration: "5m"
    retry_policy:
      max_attempts: 3
      delay_between_attempts: "1m"
  required_params:
    - destination
    - start_date
    - end_date
    - budget
    - travelers
    - trip_type
  expected_output: >
    {
      "metadata": {
        "version": "1.0",
        "timestamp": "string",
        "task_id": "string",
        "status": "success|error|partial"
      },
      "weather": {
        "temperature_range": "string",
        "conditions": "string",
        "seasonal_alerts": ["string"]
      },
      "events": {
        "holidays": ["string"],
        "festivals": ["string"],
        "special_events": ["string"]
      },
      "entry_requirements": {
        "visa": {
          "required": boolean,
          "process": "string",
          "cost": "string",
          "timeline": "string"
        },
        "health": {
          "vaccinations": ["string"],
          "covid_rules": "string",
          "insurance": "string"
        }
      }
    }
  agent: travel_searcher

flight_search_task:
  description: >
    Search flights using multiple sources for {origin} to {destination}.
    Consider: {budget}, {travelers}, {trip_type}, {start_date}, {end_date}, {flights}
  depends_on:
    - destination_search_task  # Needs destination information first
  metadata:
    version: "1.0"
    priority: 2
    estimated_duration: "10m"
    retry_policy:
      max_attempts: 3
      delay_between_attempts: "2m"
  required_params:
    - origin
    - destination
    - start_date
    - end_date
    - budget
    - travelers
  expected_output: >
    {
      "metadata": {
        "version": "1.0",
        "timestamp": "string",
        "task_id": "string",
        "status": "success|error|partial"
      },
      "errors": {
        "count": "integer",
        "details": [
          {
            "code": "string",
            "message": "string",
            "severity": "warning|error",
            "context": "string"
          }
        ]
      },
      "summary": {
        "total_options": integer,
        "price_range": {
          "lowest": "string",
          "highest": "string",
          "currency": "string"
        },
        "best_value": ["string"]
      },
      "flight_options": [
        {
          "flight_details": {
            "airline": "string",
            "flight_number": "string",
            "departure": {
              "time": "string",
              "airport": "string"
            },
            "arrival": {
              "time": "string",
              "airport": "string"
            },
            "duration": "string",
            "stops": {
              "count": integer,
              "layovers": [
                {
                  "airport": "string",
                  "duration": "string"
                }
              ]
            }
          },
          "pricing": {
            "total": "string",
            "breakdown": {
              "base": "string",
              "taxes": "string",
              "fees": "string"
            }
          }
        }
      ]
    }
  agent: travel_searcher

accommodation_search_task:
  description: >
    Search accommodations in {destination} from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}, {accomodation}
  depends_on:
    - destination_search_task  # Needs destination information first
  expected_output: >
    {
      "summary": {
        "total_options": integer,
        "price_range": {
          "lowest": "string",
          "highest": "string",
          "currency": "string"
        },
        "best_value": ["string"]
      },
      "accommodations": [
        {
          "basic_info": {
            "name": "string",
            "type": "string",
            "rating": float,
            "address": "string",
            "location": "string"
          },
          "pricing": {
            "total": "string",
            "per_night": "string",
            "fees": "string"
          },
          "features": {
            "amenities": ["string"],
            "room_types": ["string"],
            "accessibility": ["string"]
          }
        }
      ]
    }
  agent: travel_searcher

transportation_search_task:
  description: >
    Research local transportation in {destination} from {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
  expected_output: >
    {
      "summary": {
        "options": ["string"],
        "price_range": {
          "lowest": "string",
          "highest": "string",
          "currency": "string"
        }
      },
      "public_transit": {
        "types": ["string"],
        "costs": {
          "single": "string",
          "day_pass": "string",
          "weekly": "string"
        },
        "coverage": ["string"]
      },
      "private_options": {
        "taxi": {
          "availability": "string",
          "costs": "string"
        },
        "rental": {
          "types": ["string"],
          "costs": "string"
        }
      }
    }
  agent: travel_searcher

attraction_search_task:
  description: >
    Research attractions in {destination} for {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
    - transportation_search_task  # Useful to know transport options to attractions
  expected_output: >
    {
      "summary": {
        "total": integer,
        "categories": ["string"],
        "price_range": {
          "free": ["string"],
          "paid": {
            "low": "string",
            "high": "string",
            "currency": "string"
          }
        }
      },
      "attractions": [
        {
          "name": "string",
          "type": "string",
          "cost": "string",
          "timing": {
            "duration": "string",
            "hours": "string",
            "best_time": "string"
          }
        }
      ]
    }
  agent: travel_searcher

dining_search_task:
  description: >
    Research dining options in {destination}.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - destination_search_task  # Needs destination information first
    - accommodation_search_task  # Useful to know restaurant proximity to accommodation
  expected_output: >
    {
      "summary": {
        "total": integer,
        "cuisines": ["string"],
        "price_ranges": {
          "budget": ["string"],
          "mid": ["string"],
          "high": ["string"]
        }
      },
      "restaurants": [
        {
          "name": "string",
          "cuisine": "string",
          "price_range": "string",
          "location": "string",
          "highlights": ["string"]
        }
      ]
    }
  agent: travel_searcher

structure_itinerary_task:
  description: >
    Create daily itinerary from {start_date} to {end_date}.
    Consider: {travelers}, {trip_type}
  depends_on:
    - flight_search_task  # Need flight timings
    - accommodation_search_task  # Need accommodation details
    - transportation_search_task  # Need local transport options
    - attraction_search_task  # Need attraction details
    - dining_search_task  # Need dining options
  expected_output: >
    {
      "summary": {
        "days": integer,
        "highlights": ["string"]
      },
      "days": [
        {
          "date": "string",
          "activities": [
            {
              "time": "string",
              "type": "string",
              "details": "string",
              "duration": "string"
            }
          ]
        }
      ]
    }
  agent: itinerary_planner

validate_itinerary_task:
  description: >
    Validate complete itinerary for {start_date} to {end_date}.
    Consider: {budget}, {travelers}, {trip_type}. It is not needed to
    send any email.
  depends_on:
    - structure_itinerary_task  # Need the complete itinerary to validate
  expected_output: >
    {
      "validation": {
        "score": float,
        "issues": ["string"],
        "recommendations": ["string"]
      },
      "checks": {
        "timing": boolean,
        "budget": boolean,
        "feasibility": boolean
      }
    }
  agent: quality_assurance

budget_final_check_task:
  description: >
    Verify budget compliance for complete trip plan.
    Consider: {budget}, {travelers}, {trip_type}
  depends_on:
    - validate_itinerary_task  # Need validated itinerary
    - flight_search_task  # Need flight costs
    - accommodation_search_task  # Need accommodation costs
    - transportation_search_task  # Need local transport costs
    - attraction_search_task  # Need attraction costs
    - dining_search_task  # Need dining costs
  expected_output: >
    {
      "summary": {
        "total": "string",
        "remaining": "string",
        "status": "string"
      },
      "breakdown": {
        "transport": "string",
        "accommodation": "string",
        "activities": "string",
        "dining": "string",
        "other": "string"
      }
    }
  agent: budget_manager

create_travel_document_task:
  description: >
    Create a comprehensive travel document in Markdown format with all trip details.
    Consider: {start_date}, {end_date}, {travelers}, {trip_type}.
  depends_on:
    - validate_itinerary_task  # Need validated itinerary
    - budget_final_check_task  # Need final budget verification
  expected_output: >
    {
      "trip_title": "string",
      "summary": "string",
      "recommendations": ["string"],
      "practical_information": [
        {
          "title": "string",
          "content": "string",
          "resources": ["string"]
        }
      ],
      "emergency_contacts": [
        {
          "name": "string",
          "phone": "string",
          "relation": "string",
          "notes": "string"
        }
      ],
      "resources": ["string"],
      "notes": "string"
    }
  agent: quality_assurance


prepare_travel_email_task:
  description: >
    Prepare and send a beautifully formatted HTML email with all trip details to {recipient_email}.
    Convert markdown content to responsive HTML with CSS styling.
    Translate the content to {locale} language.
  depends_on:
    - create_travel_document_task  # Need the final travel document to create email
  required_params:
    - recipient_email  # Email address must be provided
    - locale  # Language preference for email content
  expected_output: >
    {
      "status": "string",
      "message": "string",
      "recipient": "string",
      "sent_timestamp": "string",
      "template": {
        "html_content": "string",
        "css_styles": "string",
        "translations": {
          "en": "string",
          "es": "string"
        }
      },
      "delivery_status": {
        "success": "boolean",
        "error": "string",
        "retry_count": "integer"
      },
      "selected_language": "string",
      "subject": {
        "en": "string",
        "es": "string"
      }
    }
  agent: quality_assurance





