name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv .venv
        . .venv/bin/activate
        uv pip install -e .[dev]
    
    - name: Lint with flake8
      run: |
        . .venv/bin/activate
        pip install flake8
        flake8 src/trip_planning tests
    
    - name: Format check with black
      run: |
        . .venv/bin/activate
        pip install black
        black --check src/trip_planning tests
    
    # - name: Run tests
    #   run: |
    #     . .venv/bin/activate
    #     python -m pytest tests/

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
    
    - name: Build Docker image
      run: docker build -t temp-image:${{ github.sha }} .
    
    - name: Scan Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'temp-image:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'